import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { once } from 'node:events';
import WebSocket from 'ws';
import { controlPlaneFixture } from './helpers/control-plane.js';
import { setControlPlaneRepositoryForTests } from '../src/storage.ts';
import { attachBridgeGateway } from '../src/bridge-gateway.ts';
import { createBridgeToken } from '../src/bridge-auth.ts';
import { bridgeRequest } from '../src/bridge-rpc.ts';
import { waitForLiveBridgeResult } from '../src/bridge-live.ts';

test('authenticated bridge isolates durable commands and live results while preserving legitimate RPC', {timeout:15000}, async t => {
  const {repository,now}=await controlPlaneFixture(t);
  const before=process.env.ORLYNX_BRIDGE_SIGNING_SECRET;
  process.env.ORLYNX_BRIDGE_SIGNING_SECRET='test-bridge-secret-with-at-least-32-bytes';
  setControlPlaneRepositoryForTests(repository);
  t.after(()=>{setControlPlaneRepositoryForTests(undefined);if(before===undefined)delete process.env.ORLYNX_BRIDGE_SIGNING_SECRET;else process.env.ORLYNX_BRIDGE_SIGNING_SECRET=before;});
  const claims={workspaceId:'ws',sessionId:'s',userId:'u',connectionId:'scope-test'};
  for(const id of ['ws','other']) await repository.putWorkspace({id,sessionId:'s',userId:'u',projectId:'p',repositoryId:1,branch:'main',provider:'orlynx-runner',state:'connecting',bridgeState:'connecting',connectionId:claims.connectionId,createdAt:now,updatedAt:now});
  const server=http.createServer();attachBridgeGateway(server);
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const socket=new WebSocket(`ws://127.0.0.1:${server.address().port}/bridge`,{headers:{Authorization:`Bearer ${createBridgeToken(claims)}`}});
  t.after(async()=>{if(socket.readyState!==WebSocket.CLOSED){const closed=once(socket,'close');socket.terminate();await closed;}await new Promise(resolve=>server.close(resolve));});
  await once(socket,'open');
  const hello=once(socket,'message');socket.send(JSON.stringify({kind:'HELLO',...claims}));
  assert.equal(JSON.parse(String((await hello)[0])).kind,'AUTHENTICATED');
  await repository.queueCommand({id:'foreign',workspaceId:'other',kind:'fs.write',payload:{},status:'queued',expiresAt:'2100-01-01T00:00:00Z',createdAt:now,updatedAt:now});
  const foreign=waitForLiveBridgeResult('foreign'),unknown=waitForLiveBridgeResult('not-queued');
  t.after(()=>{foreign.cancel();unknown.cancel();});
  let foreignResolved=false,unknownResolved=false;
  foreign.promise.then(()=>{foreignResolved=true;});unknown.promise.then(()=>{unknownResolved=true;});
  socket.send(JSON.stringify({kind:'RESULT',commandId:'foreign',ok:true,result:{saved:true}}));
  socket.send(JSON.stringify({kind:'RESULT',commandId:'not-queued',ok:true,result:{saved:true}}));
  await new Promise(resolve=>setTimeout(resolve,100));
  assert.equal((await repository.getCommand('foreign')).status,'queued','another workspace cannot complete a command');
  assert.equal(foreignResolved,false,'foreign results cannot wake RPC waiters');
  assert.equal(unknownResolved,false,'unknown results cannot wake RPC waiters');
  const stale=new WebSocket(`ws://127.0.0.1:${server.address().port}/bridge`,{headers:{Authorization:`Bearer ${createBridgeToken({...claims,connectionId:'retired-generation'})}`}});
  const staleClosed=once(stale,'close');
  const [code]=await staleClosed;
  assert.equal(code,1008,'retired credentials must be rejected before replacing the live socket');
  assert.equal(socket.readyState,WebSocket.OPEN,'stale handshake must not disconnect the current bridge');
  socket.on('message',raw=>{const frame=JSON.parse(String(raw));if(frame.kind==='COMMAND')socket.send(JSON.stringify({kind:'RESULT',commandId:frame.commandId,ok:true,result:{stdout:'verified'}}));});
  assert.deepEqual(await bridgeRequest('ws','exec',{cmd:'printf verified'},3000),{stdout:'verified'});
});
